site_name: Disease Research Notebook
site_description: Consolidated disease sources and research notes
theme:
  name: material
  palette:
    primary: indigo
  features:
    - navigation.instant
    - navigation.tabs
    - search.suggest
    - content.code.copy

# This makes sure search engines don't index the site
extra:
  generator: false
