site_name: Fundación Columbus Rare Diseases
site_description: Consolidated disease sources and research notes
theme:
  name: material
  palette:
    primary: indigo
  features:
    - navigation.instant
    - navigation.tabs
    - search.suggest
    - content.code.copy

extra_css:
- stylesheets/extra.css

# This makes sure search engines don't index the site
extra:
  generator: false
